# fly.toml app configuration file generated for morning-leaf-3462 on 2023-07-19T18:46:16-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "morning-leaf-3462"
primary_region = "atl"

[env]
  HOST = "https://morning-leaf-3462.fly.dev"
  PORT = "8081"
  SCOPES = "write_products"
  SHOPIFY_API_KEY = "YOUR_SHOPIFY_API_KEY"
  SHOPIFY_API_SECRET = "YOUR_SHOPIFY_API_SECRET"

[http_service]
  internal_port = 8081
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
